# Generated by Django 5.2.4 on 2025-08-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='assets',
            field=models.ImageField(blank=True, default='task_asset/default.jpg', null=True, upload_to='task_asset'),
        ),
    ]
